site_name: Family Music System
repo_url: https://github.com/mdsreq-fga-unb/2023.1-FamilyMusicSystem
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Home: index.md
  - Documentação: documentacao.md
theme:
  name: material
  language: pt
  favicon: images/logo-color.png
  logo: assets/logo.svg
  font:
    text: Roboto
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
  palette:
    - scheme: default
      primary: yellow
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: amber
      toggle:
        icon: material/weather-sunny
        name: Modo claro
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
