site_name: Family Music System

nav:
  - Home: index.md
  - Visão do produto e projeto:
    - Visão Geral do Produto: visao-produto-projeto/visao-produto.md
    - Visão Geral do Projeto: visao-produto-projeto/visao-projeto.md
    - Processo de Desenvolvimento de Software: visao-produto-projeto/processo-de-desenvolvimento-de-software.md
    - Lições aprendidas: visao-produto-projeto/licoes-aprendidas.md
    - Ciclo de Vida: visao-produto-projeto/ciclo-de-vida.md

theme:
  name: material
  language: pt
  favicon: images/logo-color.png
  logo: assets/logo.svg
  font:
    text: Roboto
  palette:
    - scheme: default
      primary: yellow
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: amber
      toggle:
        icon: material/weather-sunny
        name: Modo claro

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
