name: Hello GitHub Actions =

on:
    push:
        branches: ["ci-test"] 

jobs:
    build:
        runs-on: unbuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
                with:
                    node-version: 18
            - run: npm ci
            - run: npm run test:actions
            - run: npm run buid:actions
            - run: npm run deploy:actions

